###회원가입
POST http://localhost:8081/auth/register
Content-Type: application/json

{
  "birth": "2023-08-29",
  "email": "hyomyang@gmail.com",
  "firstname": "string",
  "lastName": "string",
  "password": "string",
  "phone": "string",
  "roles": [
    "ROLE_CUSTOMER", "ROLE_SELLER"
  ]
}




###로그인/hyo
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "hyomyang@gmail.com",
  "password": "string"
}

###로그인/pago
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "pagooo@naver.com",
  "password": "string"
}


###유저 정보
GET http://localhost:8081/auth/getInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06NktsaGdkZUxhY0JNUUtYUzBQR1FIZGYxSzFkMVdFWjJQZWhwZFhLNi96TT0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06Z0k3MXNnYmRlZGlxOXBqbUVadTNyUT09Iiwicm9sZXMiOlsiUk9MRV9DVVNUT01FUiIsIlJPTEVfU0VMTEVSIl0sImlhdCI6MTY5Njc5NjM1OSwiZXhwIjoxNjk2Nzk5OTU5fQ.zNzS2zQEp1m94rU0Uivql9AmzjseWvwpjsKJyNydsgQ


###유저 정보 for Module
GET http://localhost:8081/auth/getInfo/module
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06NktsaGdkZUxhY0JNUUtYUzBQR1FIZGYxSzFkMVdFWjJQZWhwZFhLNi96TT0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06Z0k3MXNnYmRlZGlxOXBqbUVadTNyUT09Iiwicm9sZXMiOlsiUk9MRV9DVVNUT01FUiIsIlJPTEVfU0VMTEVSIl0sImlhdCI6MTY5Njc5NjM1OSwiZXhwIjoxNjk2Nzk5OTU5fQ.zNzS2zQEp1m94rU0Uivql9AmzjseWvwpjsKJyNydsgQ

//eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06emhJRkw0cy9OSWNkTWEySzZwMGJwaHZhTDdieG1PR0RGYlhLcnl3MlI2Zz0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06Z0k3MXNnYmRlZGlxOXBqbUVadTNyUT09Iiwicm9sZXMiOlsiUk9MRV9TRUxMRVIiXSwiaWF0IjoxNjkzNDY0ODMxLCJleHAiOjE2OTM0Njg0MzF9.uKHFA9kmzUlFsRBWpLVfdhMZ4ZsX0Y8c3XjxANINAwM

