###물건등록
POST http://localhost:8082/seller/addProduct
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06emhJRkw0cy9OSWNkTWEySzZwMGJwaHZhTDdieG1PR0RGYlhLcnl3MlI2Zz0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06Z0k3MXNnYmRlZGlxOXBqbUVadTNyUT09Iiwicm9sZXMiOlsiUk9MRV9TRUxMRVIiXSwiaWF0IjoxNjk0OTcyMzc3LCJleHAiOjE2OTQ5NzU5Nzd9.G1Fegl_uGvmFhZDXt2XM0X5r1TUpm92vlWEZ2gP2BAQ

{
  "count": 100,
  "description": "너무좋아요",
  "items": [
  ],
  "name": "애플커피",
  "price": 100000,
  "sellerId": 1
}


###세부물건등록
POST http://localhost:8082/seller/addItem
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06emhJRkw0cy9OSWNkTWEySzZwMGJwaHZhTDdieG1PR0RGYlhLcnl3MlI2Zz0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06Z0k3MXNnYmRlZGlxOXBqbUVadTNyUT09Iiwicm9sZXMiOlsiUk9MRV9TRUxMRVIiXSwiaWF0IjoxNjk0OTcyMzc3LCJleHAiOjE2OTQ5NzU5Nzd9.G1Fegl_uGvmFhZDXt2XM0X5r1TUpm92vlWEZ2gP2BAQ

[
  {
    "count": 10,
    "name": "가스",
    "price": 10000,
    "productId": 1
  },
  {
    "count": 10,
    "name": "k9",
    "price": 100,
    "productId": 1
  }
]

###물건수정
PUT http://localhost:8082/seller/update/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06emhJRkw0cy9OSWNkTWEySzZwMGJwaHZhTDdieG1PR0RGYlhLcnl3MlI2Zz0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06Z0k3MXNnYmRlZGlxOXBqbUVadTNyUT09Iiwicm9sZXMiOlsiUk9MRV9TRUxMRVIiXSwiaWF0IjoxNjk0OTcyMzc3LCJleHAiOjE2OTQ5NzU5Nzd9.G1Fegl_uGvmFhZDXt2XM0X5r1TUpm92vlWEZ2gP2BAQ

{
  "count": 10,
  "description": "구글짱",
  "items": [
  ],
  "name": "구글커피",
  "price": 1000,
  "productId": 1
}


###세부물건 수정
PUT http://localhost:8082/seller/update/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06emhJRkw0cy9OSWNkTWEySzZwMGJwaHZhTDdieG1PR0RGYlhLcnl3MlI2Zz0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06Z0k3MXNnYmRlZGlxOXBqbUVadTNyUT09Iiwicm9sZXMiOlsiUk9MRV9TRUxMRVIiXSwiaWF0IjoxNjk0OTcyMzc3LCJleHAiOjE2OTQ5NzU5Nzd9.G1Fegl_uGvmFhZDXt2XM0X5r1TUpm92vlWEZ2gP2BAQ

{
  "count": 1,
  "itemId": 1,
  "name": "k2",
  "price": 100000
}


###상품 삭제
DELETE http://localhost:8082/seller/delete/product?productId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06emhJRkw0cy9OSWNkTWEySzZwMGJwaHZhTDdieG1PR0RGYlhLcnl3MlI2Zz0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06Z0k3MXNnYmRlZGlxOXBqbUVadTNyUT09Iiwicm9sZXMiOlsiUk9MRV9TRUxMRVIiXSwiaWF0IjoxNjk0ODAwMDA3LCJleHAiOjE2OTQ4MDM2MDd9.LdCvy1CrfPyOmS9qsVQs7yzQteg2FVLcg7YVuD2XwWU



###상세 상품 삭제
DELETE http://localhost:8082/seller/delete/item?itemId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06emhJRkw0cy9OSWNkTWEySzZwMGJwaHZhTDdieG1PR0RGYlhLcnl3MlI2Zz0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06Z0k3MXNnYmRlZGlxOXBqbUVadTNyUT09Iiwicm9sZXMiOlsiUk9MRV9TRUxMRVIiXSwiaWF0IjoxNjk0ODAwMDA3LCJleHAiOjE2OTQ4MDM2MDd9.LdCvy1CrfPyOmS9qsVQs7yzQteg2FVLcg7YVuD2XwWU

###상품 검색
GET http://localhost:8082/seller/search?name=커피&page=1&size=10&dir=ㅁsc&sort=name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06emhJRkw0cy9OSWNkTWEySzZwMGJwaHZhTDdieG1PR0RGYlhLcnl3MlI2Zz0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06Z0k3MXNnYmRlZGlxOXBqbUVadTNyUT09Iiwicm9sZXMiOlsiUk9MRV9TRUxMRVIiXSwiaWF0IjoxNjk0ODAwMDA3LCJleHAiOjE2OTQ4MDM2MDd9.LdCvy1CrfPyOmS9qsVQs7yzQteg2FVLcg7YVuD2XwWU

