

###상품 검색
GET http://localhost:8082/customer/product?name=커피&page=1&size=10&dir=asc&sort=name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06NktsaGdkZUxhY0JNUUtYUzBQR1FIZGYxSzFkMVdFWjJQZWhwZFhLNi96TT0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06TWU5cDJYd2sza3YzTENNL0NlOEthdz09Iiwicm9sZXMiOlsiUk9MRV9DVVNUT01FUiJdLCJpYXQiOjE2OTQ1MDMzNTAsImV4cCI6MTY5NDUwNjk1MH0.ijlawOwck_3lWjZIspxw3PeWbCy8PJvzKkdJYeZzYOk

###상세 상품 검색
GET http://localhost:8082/customer/product/detail?productId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06NktsaGdkZUxhY0JNUUtYUzBQR1FIZGYxSzFkMVdFWjJQZWhwZFhLNi96TT0iLCJqdGkiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPT06TWU5cDJYd2sza3YzTENNL0NlOEthdz09Iiwicm9sZXMiOlsiUk9MRV9DVVNUT01FUiJdLCJpYXQiOjE2OTQ1MDMzNTAsImV4cCI6MTY5NDUwNjk1MH0.ijlawOwck_3lWjZIspxw3PeWbCy8PJvzKkdJYeZzYOk


